  version: "3.8"
  services:
    client:
      build:
        context: ./client
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      depends_on:
        - chatbot_app

    chatbot_app:
      build:
        context: ./chatbot_app
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
